# Generated by Django 5.2.4 on 2025-08-06 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentRecord', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.IntegerField(max_length=20),
        ),
    ]
